// ─── Dashboard / Compliance mock data ────────────────────────────
// Maps to future Supabase views / edge functions.

export const EXPENSE_BY_CATEGORY = [
  { category: "Alimentação",          total: 18420, count: 230, limit: 80,   unit: "/refeição" },
  { category: "Transporte",           total: 14200, count: 71,  limit: 200,  unit: "/dia" },
  { category: "Hospedagem",           total: 26100, count: 58,  limit: 450,  unit: "/diária" },
  { category: "Combustível",          total: 6840,  count: 95,  limit: 1.20, unit: "/km" },
  { category: "Representação",        total: 12300, count: 35,  limit: 350,  unit: "/refeição" },
  { category: "Treinamento",          total: 9800,  count: 12,  limit: 3000, unit: "" },
  { category: "Software e licenças",  total: 5200,  count: 22,  limit: 150,  unit: "/dia" },
  { category: "Eventos corporativos", total: 7600,  count: 8,   limit: 5000, unit: "" },
  { category: "Passagem aérea",       total: 21500, count: 18,  limit: 2500, unit: "" },
  { category: "Material de obra",     total: 33800, count: 44,  limit: null, unit: "" },
];

export const REIMBURSEMENT_BY_DEPT = [
  { department: "Obras",          approved: 42300, pending: 8200, rejected: 3100 },
  { department: "Comercial",      approved: 27400, pending: 5600, rejected: 1800 },
  { department: "Administrativo", approved: 15200, pending: 2100, rejected: 600  },
  { department: "Financeiro",     approved: 9800,  pending: 1400, rejected: 400  },
  { department: "TI",             approved: 7300,  pending: 1100, rejected: 200  },
  { department: "RH",             approved: 4200,  pending: 600,  rejected: 100  },
];

export const MONTHLY_VOLUME = [
  { month: "Dez/25", total: 38200, violations: 12 },
  { month: "Jan/26", total: 44100, violations: 9  },
  { month: "Fev/26", total: 39800, violations: 14 },
  { month: "Mar/26", total: 51200, violations: 7  },
  { month: "Abr/26", total: 47600, violations: 11 },
  { month: "Mai/26", total: 34900, violations: 5  },
];

export const POLICY_VIOLATIONS = [
  {
    id: "v-01",
    severity: "high",
    type: "above_limit",
    employee: "Rafael Souza",
    department: "Obras",
    category: "Hospedagem",
    amount: 680,
    limit: 450,
    excess: 230,
    date: "2026-05-19",
    description: "Despesa R$ 230 acima do limite de R$ 450/diária",
  },
  {
    id: "v-02",
    severity: "high",
    type: "missing_docs",
    employee: "Carlos Almeida",
    department: "Obras",
    category: "Representação",
    amount: 820,
    limit: 350,
    excess: 470,
    date: "2026-05-18",
    description: "Nota fiscal ausente · excede limite em R$ 470",
  },
  {
    id: "v-03",
    severity: "medium",
    type: "missing_docs",
    employee: "Fernanda Lima",
    department: "Comercial",
    category: "Alimentação",
    amount: 95,
    limit: 80,
    excess: 15,
    date: "2026-05-18",
    description: "Nota fiscal ausente",
  },
  {
    id: "v-04",
    severity: "medium",
    type: "above_limit",
    employee: "Bruno Mendes",
    department: "TI",
    category: "Software e licenças",
    amount: 210,
    limit: 150,
    excess: 60,
    date: "2026-05-17",
    description: "Despesa R$ 60 acima do limite diário",
  },
  {
    id: "v-05",
    severity: "medium",
    type: "no_approval",
    employee: "Tatiane Rocha",
    department: "Administrativo",
    category: "Hospedagem",
    amount: 1350,
    limit: 450,
    excess: null,
    date: "2026-05-16",
    description: "3 diárias sem pré-aprovação registrada",
  },
  {
    id: "v-06",
    severity: "low",
    type: "above_limit",
    employee: "Fernanda Lima",
    department: "Comercial",
    category: "Transporte",
    amount: 245,
    limit: 200,
    excess: 45,
    date: "2026-05-15",
    description: "Despesa R$ 45 acima do limite diário",
  },
  {
    id: "v-07",
    severity: "low",
    type: "missing_docs",
    employee: "Rafael Souza",
    department: "Obras",
    category: "Combustível",
    amount: 186,
    limit: null,
    excess: null,
    date: "2026-05-14",
    description: "Registro de odômetro ausente",
  },
];

export const COMPLIANCE_SCORE = 84; // 0–100

export const KPI_SUMMARY = {
  total_submitted:  312,
  total_approved:   271,
  total_pending:    28,
  total_rejected:   13,
  total_amount:     155760,
  avg_per_employee: 3680,
  violations_open:  7,
  violations_30d:   58,
};